spring:
  application:
    name: team-intro-service
  profiles:
    active: prod

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true